[package]
name = "wayshot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = { version = "0.5.4", package = "gtk4" }
wayland-client = "0.29.5"
wayland-protocols = "0.29.5"
